### PR TITLE
Removed hardcoded sqlite database in main code

### PR DESCRIPTION
**Pull request by Beutlin**

### CODE REVIEW

**Comment by EDDYMENS** [comment]
Sqlite is still supported within the engine although not compatible with most DB queries within the Engine. In other to have a complete PR , the select option in  `resource/views/services/create.blade.php` and `resource/views/services/edit.blade.php`  need to be taken out 
screenshot from 2018-04-16 08-06-54

**Comment by Beutlin** [comment]
My intention is to use a SQLITE database. I've created one and saved the setting within the .env File.
Everything worked until I tried to install an extension. I got some errors that a database "devless-rec.sqlite3" is missing.
After some investigations I saw that the removed line overrides my database settings and therefore I have all these issues.

I donnot know the consequences but I think it is wrong to override user-specified .env Settings without any check.

If you really need devless-rec.sqlite3 for some reason, than you can also add a "empty($database)" check:
```
  if ($driver == 'sqlite' && empty($database)) {
            $database = database_path('devless-rec.sqlite3');
   }
```

**Comment by EDDYMENS** [comment]
Aaah I get you now. Then the best option is to include the `empty` check. Also can you please highlight a little bit more why you want to go with sqlite.

**Comment by Beutlin** [comment]
In my opinion sqlite is a nice database format for small projects. It is easy to setup, change, backup.
Other databases require a running service, a database user and it is difficul to snapshot the data and reset it later after some trials.

**Comment by Beutlin** [comment]
I've create a new pull request #94.
This one is closed.

**Pull request closed without merging**
